name: Building GXDE Testing Package (zhuangzhuang)
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_call:
    secrets:
      PASSWD:
        required: true
      USERS:
        required: true
      HOST: 
        required: true
      UPATH: 
        required: true
      UPROGRAM: 
        required: true
      UPORT: 
        required: true

env:
  REPOSITORY: https://github.com/GXDE-OS/GXDE  
  BOTTLEPATH: system-bottle

jobs:  
  call-amd64-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: amd64-zhuangzhuang
      arch: amd64
      rootfs-codename: trixie
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang

  call-arm64-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base-arm64.yml@master
    secrets: inherit
    with:
      display-name: arm64-zhuangzhuang
      arch: arm64
      rootfs-codename: trixie
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang

  call-mips64el-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: mips64el-zhuangzhuang
      arch: mips64el
      rootfs-codename: sid
      rootfs-source: https://mips-repo.gxde.top/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang

  call-riscv64-zhuangzhuang:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base-riscv64.yml@master
    secrets: inherit
    with:
      display-name: riscv64-zhuangzhuang
      arch: riscv64
      rootfs-codename: trixie
      rootfs-source: https://deb.debian.org/debian/
      gxde-codename: lizhi
      gxde-codename-upload: zhuangzhuang
