name: Building GXDE Package (meimei)
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_call:
    secrets:
      PASSWD:
        required: true
      USERS:
        required: true
      HOST: 
        required: true
      UPATH: 
        required: true
      UPROGRAM: 
        required: true
      UPORT: 
        required: true

env:
  REPOSITORY: https://github.com/GXDE-OS/GXDE  
  BOTTLEPATH: system-bottle

jobs:  
  call-loong64-meimei:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-base.yml@master
    secrets: inherit
    with:
      display-name: loong64-meimei
      arch: loong64
      rootfs-codename: loongnix
      rootfs-source: https://pkg.loongnix.cn/loongnix/25
      gxde-codename: meimei
      gxde-codename-upload: meimei
